### ISSUE TITLE
Possibility of adding Theme

### ISSUE THREAD

**Issue by Prudence97** [sambhavsaxena/fortlax.io#12]
I love that the dark mode adds to the entire incognito and private feel. 

It would however be nice to have a light and dark mode toggle, for does that want the more official feel to their conversation.

It's amazing either ways

**Comment by sambhavsaxena** [comment]
Thanks but I don't think people would use this utility for official purposes.
Also I just wanted it to be really minimal with the interface so.
Maybe in the coming days, I might consider this as an option.

**Comment by Prudence97** [comment]
That's also right.

You made a beautiful app.
I'll be closing the issue now
