### ISSUE TITLE
cant seem to copy the project directly in vercel

### ISSUE THREAD

**Issue by Ayesha420420** [sambhavsaxena/fortlax.io#13]

**Comment by sambhavsaxena** [comment]
can you elaborate a little? what steps did you follow exactly?

**Comment by Ayesha420420** [comment]
i simply tried to clone the repository into my vercel but it throwed some errors and is not deploying

**Comment by sambhavsaxena** [comment]
@Ayesha420420 
I have modified the `build` and `start` commands on vercel because both server and client installs from the same repository but on different platforms, and [package.json](https://github.com/sambhavsaxena/fortlax.io/blob/main/package.json) doesn't match the deployed version.

**Comment by Ayesha420420** [comment]
so what could be the easiest way to deploy it without any hassle ? I thought its would be just a one click install through vercel as you are hosting yourself on it

**Comment by Ayesha420420** [comment]
@sambhavsaxena Also, A suggestion as you have created a great app and i would love to copy it but if you could change the UI of the chatroom similar to this [blabber.vercel.app/](https://blabber.vercel.app/) would be really nice. The blabber project is also on github so do check it out

**Comment by sambhavsaxena** [comment]
vercel is super fast for hosting static web apps, but for backend I prefer using [render.com](https://render.com/), and its pretty straight forward, you just need to configure the server directory like I did [here](https://github.com/sambhavsaxena/fortlax.io/blob/main/src/socketContext.js#L7) and it'll work.

Also I checked out Blabber, for some reason it doesn't seem to work right now, but yes it's UI actually looks fine. I wanted to keep mine minimal + easy to use, and hence less features (and this actually works).

**Comment by Ayesha420420** [comment]
@sambhavsaxena Great, I will give it a try through render and if came accross any problem, will ask for your help. Thank you ! plus yeah blabber does not seem to work but i just suggested the chatroom once you create room, the ui looks more friendly to chat and invite friends. great work btw

**Comment by Ayesha420420** [comment]
@sambhavsaxena Where do i need to configure the server in render after creating account ? and also i want it to be deployed on vercel like yours, so is that step for later ?

**Comment by Ayesha420420** [comment]
Deployed the whole project on render but keeps on loading when i enter username and roomname

**Comment by sambhavsaxena** [comment]
> so is that step for later

yes, first deploy the server on render, from there you'll get a server endpoint for accessing it.
then go over to vercel and add the server url to environment variables in this format.

![Screenshot_20230713_175357](https://github.com/sambhavsaxena/fortlax.io/assets/76242518/fb1c84f1-0f8b-4db9-9c85-21f677fae2fd)

**Comment by Ayesha420420** [comment]
server deployment failed. can you join fix room in your own chat so i can set it up faster as i am feeling dumb right now

**Comment by sambhavsaxena** [comment]
paste the screenshot of failed deployment here

**Comment by Ayesha420420** [comment]
![image](https://github.com/sambhavsaxena/fortlax.io/assets/88076426/93e1a93a-9548-44ec-bcc4-a74971559824)

**Comment by sambhavsaxena** [comment]
![Screenshot_20230713_184240](https://github.com/sambhavsaxena/fortlax.io/assets/76242518/2c0742dd-7db2-43aa-831b-d7662b3c528b)

**Comment by Ayesha420420** [comment]
![image](https://github.com/sambhavsaxena/fortlax.io/assets/88076426/6be0746d-9c8b-4c6d-930b-32c3a0b53c76)

still gave error :(

**Comment by sambhavsaxena** [comment]
one last thing you could do is to change the build and start commands to `npm install` and `npm start` resp.

**Comment by Ayesha420420** [comment]
![image](https://github.com/sambhavsaxena/fortlax.io/assets/88076426/336d0aa2-a691-440f-b887-52efdf173797)
![Screenshot 2023-07-13 4 24 32 PM](https://github.com/sambhavsaxena/fortlax.io/assets/88076426/83826ad7-2f72-4e1c-b0f4-72def91d1aa6)


No difference tried changing the build and start command aswell

**Comment by Ayesha420420** [comment]
its always giving error after 1 minute into deployment, you can join the same room to help

**Comment by sambhavsaxena** [comment]
can't really say what's causing the error, there's a certain combination of build and start commands to select and one of them works, for me its the default settings that worked.
![image](https://github.com/sambhavsaxena/fortlax.io/assets/76242518/59849b4c-451c-4617-b746-e1466cae11fd)

**Comment by Ayesha420420** [comment]
This error has nothing to do with the server right ?

**Comment by sambhavsaxena** [comment]
rigth, your server is up and running.

**Comment by Ayesha420420** [comment]
can you try deploying it as a new project yourself and see if it shows you the error aswell ?

**Comment by sambhavsaxena** [comment]
okay so i tried redeploying it and looks like there's an issue with vercel not allowing legacy dependencies to be installed on its platform, to fix that I had to clone the repo and fix the dependency versions by running `npm audit fix --force` and then push the code again into production.

**Comment by Ayesha420420** [comment]
join the room fix please so its easier for me to do it aswell. do i need to do the same now ? and how ?

**Comment by sambhavsaxena** [comment]
@Ayesha420420 the changes have been deployed, thanks for raising the issue:)

**Comment by Ayesha420420** [comment]
@sambhavsaxena For some reason it is still throwing me errors. I copied your repository and did the same steps i was suppose to and it gave me error !

![image](https://github.com/sambhavsaxena/fortlax.io/assets/88076426/839a3169-1945-4ee5-ab20-0092aa84c39d)

**Comment by sambhavsaxena** [comment]
reverted the installation further, check if it works now, seem to be a problem with vercel!

**Comment by Ayesha420420** [comment]
@sambhavsaxena Done done done ! thanks , got reployed just now ! thanks alot
